services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: explorewithme
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data
      - ./statSvc/server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./statSvc/server/src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d explorewithme"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  stats-db-data: