services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: explorewithme
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data
      - ./statSvc/server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./statSvc/server/src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d explorewithme"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: ./statSvc/server
      dockerfile: Dockerfile
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explorewithme
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    restart: unless-stopped

  ewm-service:
    build:
      context: .  # или путь к основному сервису
      dockerfile: Dockerfile-main  # нужен другой Dockerfile
    container_name: ewm-service
    environment:
    # настройки основного сервиса
    ports:
      - "8080:8080"
    depends_on:
      - stats-db
      - stats-server
    restart: unless-stopped

volumes:
  stats-db-data: