version: '3.8'

services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: explorewithme
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data
      - ./stat-svc/server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./stat-svc/server/src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d explorewithme"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-server:
    build:
      context: ./stat-svc/server
      dockerfile: Dockerfile
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/explorewithme
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    restart: unless-stopped

  main-service:
    build: ./main-svc
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewmdb
      - stat-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewmdb:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewm
      - SPRING_DATASOURCE_PASSWORD=ewm
      - SERVICES_STATSSERVICE_URI=http://stat-server:9090
    #   - JAVA_OPTS=-Djdk.httpclient.HttpClient.log=errors,requests

  ewmdb:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewmdb
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

volumes:
  stats-db-data: