server:
  port: 8080

stat-svc:
  client: http://stats-serve:9090

logging:
  level.org.springframework.orm.jpa: INFO
  level.org.springframework.transaction: INFO
  level.org.springframework.transaction.interceptor: TRACE
  level.org.springframework.orm.jpa.JpaTransactionManager: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/main_svc_db
    driverClassName: org.postgresql.Driver
    username: dbuser
    password: 12345